### ISSUE TITLE
Files inside symbolic links are returned by `childOf` and `descendentOf`

### ISSUE THREAD

**Issue by capitanbatata** [Gabriel439/Haskell-DirStream-Library#10]
Probably this is desired, however in the current state of the library I don't know how to avoid getting files (which are not symbolic links) that are under directories that are symbolic links.

The use case is quite simple, count the lines of all the files under a directory:
    https://github.com/capitanbatata/sandbox/blob/master/pw-pipes/src/Lib.hs

Probably the approach I took in the example above is wrong, and this feature is not needed. But if it is, then I'd be happy to submit a pull request.

**Comment by Gabriel439** [comment]
Assuming that you have a function that can return whether or not to descend into a file:

```haskell
descend :: FilePath -> IO Bool
```

... then you can write your own custom descent function like this:

```haskell
myDescendentOf :: MonadSafe m => F.FilePath -> ListT m F.FilePath
myDescendentOf path = do
    child    <- childOf path
    isDir    <- liftIO $ isDirectory child
    continue <- liftIO $ descend child
    if isDir && continue
        then return child <|> myDescendentOf child
        else return child
```

**Comment by capitanbatata** [comment]
Thanks for the promp answer Gabriel. I see two issues (probably because of my lack of experience with IO in Haskell and Pipes):

0. `descend` will be a an expensive function, since I have to take the path prefixes and check whether any of them is a directory and a symbolic link.
1. The implementation of `myDescentOf` is almost identical to `descentOf`.

I was wondering how the symbolic links are handled in the use cases of `descentOf`.

**Comment by Gabriel439** [comment]
Why would you need to check the path prefixes?  You can just check the full path to see if it is a symlink

There is nothing wrong with `myDescendentOf` being a slight variation on `descendentOf`.  The entire reason why `ListT` has a `MonadPlus` instance is so that users can write their own custom descent functions instead of requiring a one-size-fits-all descent functions

**Comment by capitanbatata** [comment]
> There is nothing wrong with myDescendentOf being a slight variation on descendentOf.
That is the way I chose at the end. I was just wondering what is the use of `descentOf` since it will return duplicated paths in the case of directories that are symlinks.

All in all, it is clear now how to proceed in this situation. Thanks for the support.
