### ISSUE TITLE
"descendant" is misspelled

### ISSUE THREAD

**Issue by FranklinChen** [Gabriel439/Haskell-DirStream-Library#5]
"descendant" is misspelled "descendent" throughout.

**Comment by Gabriel439** [comment]
I actually looked this up at the time to make sure I had the right version: http://grammarist.com/usage/descendant-descendent/

**Comment by FranklinChen** [comment]
I knew of the alternate spelling, but it is used so rarely (this may be the first time in two or three decades that I saw this spelling) that I considered it a "misspelling" for all practical purposes, e.g. I verified that Google search says "Did you mean descendant": the big data have spoken :-).

**Comment by Gabriel439** [comment]
Yeah, I was on the edge about which was the correct spelling myself.  I'll go ahead and mark this closed since the all-knowing Google has spoken. :)
