### ISSUE TITLE
pipes version bound might be unnecessary narrow

### ISSUE THREAD

**Issue by rickynils** [Gabriel439/Haskell-DirStream-Library#8]
Latest nixpkgs master bumped `pipes` to 4.3.2. `dirstream` seems to build fine when the `pipes < 4.3` bound is removed.

**Comment by patrickt** [comment]
Agreed. This would be really good.

**Comment by Gabriel439** [comment]
This is fixed and up on Hackage as `dirstream-1.0.2`
